### ISSUE TITLE
mocha测试问题

### ISSUE THREAD

**Issue by dachengzi000** [violetjack/VueStudyDemos#2]
VueTestDemo中单元测试 mocha Hello.spec.js时 会指出import错误，这个问题怎么处理呢

**Comment by violetjack** [comment]
首先，Vue项目中是用Karma来运行测试的，正如我在 README 中写的那样运行`npm run unit`来进行测试的，而从 `package.json` 文件中可以看到执行的脚本：
```
cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run
```
然后，如果是要用 mocha来进行单元测试，有 `import` 这类 ES6 的语法的需要进行 ES6 转码，具体看一下阮一峰老师的[测试框架 Mocha 实例教程](http://www.ruanyifeng.com/blog/2015/12/a-mocha-tutorial-of-examples.html)的第八点。

希望能够帮助到你，谢谢~

**Comment by dachengzi000** [comment]
感谢你的回复，我再研究下

**Comment by dachengzi000** [comment]
@violetjack 楼主，我还想问下，项目中我用了vux UI库，在搭建测试框架时，PhantomJS 报错，语法错误，‘const’ 单元测试没跑起来，这个难道只能测vue原生的代码么

04 01 2018 16:04:47.454:WARN [karma]: No captured browser, open http://localhost:9876/
04 01 2018 16:04:47.469:INFO [karma]: Karma v2.0.0 server started at http://0.0.0.0:9876/
04 01 2018 16:04:47.470:INFO [launcher]: Launching browser PhantomJS with unlimited concurrency
04 01 2018 16:04:47.601:INFO [launcher]: Starting browser PhantomJS
04 01 2018 16:04:50.722:INFO [PhantomJS 2.1.1 (Windows 8 0.0.0)]: Connected on socket YFbh_c4N9ynQoZNJAAAA with id 83272403
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  {
    "message": "SyntaxError: Unexpected token 'const'\nat webpack:///~/_vux@2.5.8@vux/src/libs/router.js:3:0 <- index.js:1192",
    "str": "SyntaxError: Unexpected token 'const'\nat webpack:///~/_vux@2.5.8@vux/src/libs/router.js:3:0 <- index.js:1192"
  }

PhantomJS 2.1.1 (Windows 8 0.0.0): Executed 0 of 0 SUCCESS (0 secs / 0 secs)
TOTAL: 0 SUCCESS


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
=================================

**Comment by violetjack** [comment]
const是ES6语法，你换成ES5写法。或者安装babel来解决这个问题。具体没研究过……晚上我试试去。

**Comment by violetjack** [comment]
vux 单元测试肯定是可以用的，它的源码中就有[单元测试](https://github.com/airyland/vux/blob/v2/test/unit/dateFormat.spec.js)

**Comment by dachengzi000** [comment]
嗯 我看了一下，我是这么写的
"scripts": {
        "dev": "node build/dev-server.js",
        "start": "node build/dev-server.js",
        "build": "node build/build.js",
        "unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",
        "test": "npm run unit"
    },

demo中是
"scripts": {
        "dev": "node build/dev-server.js",
        "start": "node build/dev-server.js",
        "build": "node build/build.js",
        "unit": "cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run",
        "e2e": "node test/e2e/runner.js",
        "test": "npm run unit && npm run e2e",
        "lint": "eslint --ext .js,.vue src test/unit/specs test/e2e/specs"
    }
暂时不需要eslint,我给去掉了

然后，npm err
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 163@1.0.0 unit: `cross-env BABEL_ENV=test karma start test/unit/karma.conf.js --single-run`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 163@1.0.0 unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dachengzi\AppData\Roaming\npm-cache\_logs\2018-01-04T07_47_41_317Z-debug.log

是我script中配置的不对么，理论上是正确的哈

**Comment by violetjack** [comment]
你好，这个 issue 的问题解决了吗？如未解决我们可以再来讨论交流这个这个问题。之前忘记回复了~实在抱歉。如果已解决还请告知，我将关闭 issue
