### ISSUE TITLE
hi,大神请教您一个问题，为什么需要emit两次呢。非常感谢

### ISSUE THREAD

**Issue by DaZhaoLis** [violetjack/VueStudyDemos#5]
https://github.com/violetjack/VueStudyDemos/blob/75d9f735c8032ff3051b797c3f30016a0b2dc30f/ElementCode/src/utils/vue-popper.js#L69

watch: {
    value: {
      immediate: true,
      handler(val) {
        this.showPopper = val; // 这里emit一次input
        this.$emit('input', val);  //再次emit?why？
      }
    },

    showPopper(val) {
      val ? this.updatePopper() : this.destroyPopper();
      this.$emit('input', val);
    }
  },

**Comment by violetjack** [comment]
额……看了下 element 的 commit history，从[这里](https://github.com/ElemeFE/element/commit/b808879ddbd928a366288bbde91d38e2b6155825#diff-cb3efcfdf157956fce0480ea920e5e5c)可以看到两个 $emit 是同时添加进去的。
看着我也感觉好像第一个 emit 可以去掉的样子：
```js
  watch: {
    value: {
      immediate: true,
      handler(val) {
        this.showPopper = val;
        // this.$emit('input', val);
      }
    },

    showPopper(val) {
      val ? this.updatePopper() : this.destroyPopper();
      this.$emit('input', val);
    }
  },
```
我猜测应该有情况会走不到 `showPopper()` 的监听方法中去，比如 `showPopper` 默认为 false，而 `value` 也传入 false ，由于 `immediate` 立即执行监听方法，此时 `showPopper` 是 `false => false`，不触发变化监听。
以上只是个人猜测，如有错误还请指出，谢谢！

**Comment by DaZhaoLis** [comment]
嗯嗯，感谢您大神。
      我就是看了提交记录是这样所以找不到答案，不知道您有没有发先饿了么的旧ui库，其实有些提交记录可以在这里找到：https://github.com/freeze-component
我也有想到immediate这个。我加了饿了么的人微信，等他问了黄奕老师再update这个帖子

**Comment by violetjack** [comment]
好的，期待你的分享 :)
