### ISSUE TITLE
为什么需要剔除 v-开头的属性呢？

### ISSUE THREAD

**Issue by DaZhaoLis** [violetjack/VueStudyDemos#6]
https://github.com/violetjack/VueStudyDemos/blob/75d9f735c8032ff3051b797c3f30016a0b2dc30f/ElementCode/src/utils/vue-popper.js#L69

appendArrow(element) {
      let hash;
      if (this.appended) {
        return;
      }

      this.appended = true;

      for (let item in element.attributes) {
        if (/^_v-/.test(element.attributes[item].name)) {   //为什么这里需要剔除v-开头的属性呢
          hash = element.attributes[item].name;
          break;
        }
      }

      const arrow = document.createElement('div');

      if (hash) {
        arrow.setAttribute(hash, '');
      }
      arrow.setAttribute('x-arrow', '');
      arrow.className = 'popper__arrow';
      element.appendChild(arrow);
    }
  },

**Comment by violetjack** [comment]
首先，正则要获取的是第一个以 `_v-` 开头的属性名，而非剔除。
然后，代码的目的是为 arrow 元素添加一个 `_v-` 开头的属性和 `x-arrow` 属性。具体这两个属性干啥用的没研究过。
最后，以上论述可以通过测试用例证明：
```js
  it('appendArrow: add scoped', () => {
    const popper = document.createElement('div');
    popper.setAttribute('_v-110', true);
    const vm = createTest(CleanPopper, {
      reference: document.createElement('div'),
      visibleArrow: true,
      popper
    });
    expect(vm.appended).to.empty;
    vm.createPopper();
    expect(vm.popperJS._popper.querySelector('[x-arrow][_v-110]')).to.exist;
  });
```
断言最后使用[属性选择器](https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Introduction_to_CSS/Attribute_selectors)获取到了元素。

**Comment by DaZhaoLis** [comment]
非常感谢您的回答。
x-arrow是用于标识popper箭头元素。

**Comment by violetjack** [comment]
好的，我之后会写一篇关于 poper 的博客学习下的~
